$ErrorActionPreference = "Stop"

$htmlPath = "index.html"
$cssPath = "css/style.css"
$outputPath = "mobile_index.html"

Write-Host "Reading HTML from $htmlPath..."
$html = Get-Content $htmlPath -Raw -Encoding UTF8

Write-Host "Reading CSS from $cssPath..."
$css = Get-Content $cssPath -Raw -Encoding UTF8

# Derive the JS file list from index.html's own <script src="js/...."> tags,
# in document order, so this list can never drift out of sync with the app shell.
$scriptTagMatches = [regex]::Matches($html, '<script src="(js/[^"]+)"></script>')
$jsFiles = $scriptTagMatches | ForEach-Object { $_.Groups[1].Value }

Write-Host "Reading JS files (in index.html's script order)..."
$jsContent = ""
foreach ($file in $jsFiles) {
    if (Test-Path $file) {
        Write-Host "  Adding $file"
        $content = Get-Content $file -Raw -Encoding UTF8
        $jsContent += "`n/* --- $file --- */`n" + $content + "`n"
    } else {
        Write-Warning "File not found: $file"
    }
}

# Embed CSS
Write-Host "Embedding CSS..."
$html = $html -replace '<link rel="stylesheet" href="css/style.css">', "<style>`n$css`n</style>"

# Remove existing script tags in the body
# We filter out lines that load the JS files we just bundled
Write-Host "Removing old script tags..."
$lines = $html -split "`n"
$filteredLines = $lines | Where-Object { $_ -notmatch '<script src="js/' }
$html = $filteredLines -join "`n"

# Inject JS before </body>
Write-Host "Injecting bundled JS..."
$html = $html -replace '</body>', "<script>`n$jsContent`n</script>`n</body>"

# Mark the output as generated so nobody hand-edits it again (that drift is what
# this build script exists to eliminate).
$banner = "<!--`n  AUTO-GENERATED by build.ps1 from index.html + css/style.css + js/*.js.`n  Do not edit this file directly - edit the source files and re-run build.ps1.`n-->`n"
$html = $html -replace '(?s)^(<!DOCTYPE html>\r?\n)', "`$1$banner"

Write-Host "Writing output to $outputPath..."
$html | Set-Content $outputPath -Encoding UTF8
Write-Host "Build complete!"
