// Cross-platform replacement for build.ps1: bundles index.html + css/style.css +
// the js/*.js files listed in index.html into the single-file mobile_index.html.
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8').replace(/^﻿/, '');

let html = read('index.html');
const css = read('css/style.css');

const jsFiles = [...html.matchAll(/<script src="(js\/[^"]+)"><\/script>/g)].map((m) => m[1]);
let js = '';
for (const f of jsFiles) js += `\n/* --- ${f} --- */\n` + read(f) + '\n';

html = html.replace('<link rel="stylesheet" href="css/style.css">', () => `<style>\n${css}\n</style>`);
html = html.split('\n').filter((l) => !/<script src="js\//.test(l)).join('\n');
html = html.replace('</body>', () => `<script>\n${js}\n</script>\n</body>`);

const banner =
  '<!--\n  AUTO-GENERATED by scripts/build-legacy.mjs from index.html + css/style.css + js/*.js.\n' +
  '  Do not edit this file directly - edit the source files and run: npm run build:legacy.\n-->\n';
html = html.replace(/^(<!DOCTYPE html>\r?\n)/, (_, d) => d + banner);

fs.writeFileSync(path.join(root, 'mobile_index.html'), html.endsWith('\n') ? html : html + '\n');
console.log(`mobile_index.html built from ${jsFiles.length} scripts`);
